import type { FeaturedProduct } from "@/types/featured-product";

export const FEATURED_PRODUCTS: FeaturedProduct[] = [
  {
    slug: "olio-mimi-coratina",
    name: "Olio Mimì Coratina 500ml",
    producer: "Az. Agr. Donato Conserva",
    producerSlug: "az-agr-donato-conserva",
    region: "Puglia",
    country: "Italy",
    cultivar: "Coratina",
    intensity: "Robust",
    category: "olive-oil",
    organic: false,
    signatureAward: "Bibenda 5 Drops",
    awardYear: 2026,
    imagePath: "/images/bottles/mimi-coratina-tm.png",
    tastingNotes: ["Artichoke", "Tomato Leaf", "Wild Herbs", "Bitter Almond", "Black Pepper"],
    pairings: ["Grilled Red Meat", "Aged Pecorino", "Bean Soups", "Bruschetta", "Cured Meats"],
    description:
      "Olio Mimì Coratina is a robust monovarietal from Puglia, pressed from estate-grown Coratina olives at peak green ripeness. Layered bitterness and pronounced pungency frame notes of artichoke, tomato leaf, and bitter almond, finishing long and warming.",
    producerBlurb:
      "Az. Agr. Donato Conserva manages the entire supply chain across roughly 45 hectares of Apulian groves. Olives are harvested at optimal ripeness, milled within hours, then immediately filtered and stored under inert gas to preserve aromatic intensity.",
    pricing: { originalCny: 457, saleCny: 388, discountPct: 15 },
    freshnessTag: {
      bestBefore: "Best Before: 20 Feb 2027",
      storage: ["Climate-Controlled Storage · 稳控仓储"],
    },
    cardAwards: [
      "Flos Olei 2026 · 99/100",
      "Bibenda 2026 · 5 Gocce",
      "JOOP 2025 · Gold · Monovarietal",
    ],
    awards: [
      "Flos Olei 2026 · 99/100",
      "Bibenda 2026 · 5 Gocce",
      "JOOP Japan Olive Oil Prize 2025 · Gold · Monovarietal Coratina",
      "Olive Japan 2025 · Gold · Monovarietal Coratina",
      "Sol d'Oro 2026 · Gran Menzione · Monovarietal Coratina",
    ],
  },
  {
    slug: "fonte-di-foiano-grand-cru",
    name: "Fonte di Foiano Grand Cru 500ml",
    producer: "Società Agricola Fonte di Foiano",
    producerSlug: "fonte-di-foiano",
    region: "Tuscany",
    country: "Italy",
    cultivar: "Picholine",
    intensity: "Robust",
    category: "olive-oil",
    organic: false,
    signatureAward: "Flos Olei 99/100",
    awardYear: 2026,
    imagePath: "/images/bottles/fonte-di-foiano-grand cru.png",
    tastingNotes: ["Cut Grass", "Fresh Thistle", "Apple Skin", "Mint", "White Pepper"],
    pairings: ["Florentine Steak", "Tuscan Bean Soup", "Bitter Greens", "Pecorino Toscano", "Carpaccio"],
    description:
      "Grand Cru is the flagship cuvée from Fonte di Foiano: a robust Picholine selection grown on Tuscan hillsides above the Maremma. Cut grass and fresh thistle dominate the nose, with apple skin and mint on the palate and assertive pepper through the finish.",
    producerBlurb:
      "Società Agricola Fonte di Foiano farms over a hundred hectares of olive groves in the Tuscan hills, picking by hand and milling the same day in a cold-extraction plant calibrated for low oxygen exposure and full retention of polyphenolic intensity.",
    pricing: { originalCny: 568, saleCny: 284, discountPct: 50 },
    freshnessTag: {
      bestBefore: "Best Before: 19 May 2026",
      storage: ["Climate-Controlled Storage", "稳控仓储 · 避光保存"],
      guarantee: "Quality Guaranteed",
    },
    subtitle:
      "Società Agricola Fonte di Foiano · Castagneto Carducci, Bolgheri · Tuscany",
    cardAwards: [
      "Flos Olei 2026 · Farm of the Year · 99/100",
      "Gambero Rosso · Tre Foglie · 10 Consecutive Years",
      "Bibenda 2025 · 5 Gocce",
      "Il Magnifico 2026 · Europe's Best EVOO",
    ],
    awards: [
      "🏆 Flos Olei 2026 · The Best · Farm of the Year · 99/100",
      "🏆 Flos Olei 2025 · 99/100",
      "🏆 Flos Olei 2024 · 99/100",
      "🏆 Il Magnifico 2026 · Europe's Best EVOO · Collection 2026",
      "⭐ Gambero Rosso · Tre Foglie · 10 consecutive years · Annual Star",
      "🌿 Bibenda 2025 · 5 Gocce",
      "🌍 Exported to 30+ countries worldwide",
    ],
  },
  {
    slug: "fonte-di-foiano-riflessi",
    name: "Fonte di Foiano Riflessi 500ml",
    producer: "Società Agricola Fonte di Foiano",
    producerSlug: "fonte-di-foiano",
    region: "Tuscany",
    country: "Italy",
    cultivar: "Maurino",
    intensity: "Medium",
    category: "olive-oil",
    organic: false,
    signatureAward: "Gambero Rosso 3 Leaves",
    awardYear: 2026,
    imagePath: "/images/bottles/riflessi.png",
    tastingNotes: ["White Flowers", "Green Almond", "Apple", "Light Tomato", "Soft Pepper"],
    pairings: ["White Fish", "Burrata", "Spring Vegetables", "Pesto Pasta", "Spring Salads"],
    description:
      "Riflessi is a medium-intensity Maurino from Fonte di Foiano. A floral entry of white blossom and green almond opens onto stone fruit and a clean, balanced bitterness. The finish is gently peppery, designed for everyday table use without overshadowing delicate ingredients.",
    producerBlurb:
      "Società Agricola Fonte di Foiano works each cultivar as a single-estate selection, fermenting nothing and bottling within weeks of harvest. Maurino fruit is picked early to keep aromatic delicacy front and center.",
    pricing: { originalCny: 558, saleCny: 279, discountPct: 50 },
    freshnessTag: {
      bestBefore: "Best Before: 19 May 2026",
      storage: ["Climate-Controlled Storage", "稳控仓储 · 避光保存"],
      guarantee: "Quality Guaranteed",
    },
    subtitle:
      "Società Agricola Fonte di Foiano · Castagneto Carducci, Bolgheri · Tuscany",
    cardAwards: [
      "Flos Olei 2026 · Farm of the Year · 99/100",
      "Gambero Rosso · Tre Foglie · 10 Consecutive Years",
      "Bibenda 2025 · 5 Gocce",
    ],
    awards: [
      "🏆 Flos Olei 2026 · The Best · Farm of the Year · 99/100",
      "🏆 Flos Olei 2025 · 99/100",
      "🏆 Flos Olei 2024 · 99/100",
      "⭐ Gambero Rosso · Tre Foglie · 10 consecutive years · Annual Star",
      "🌿 Bibenda 2025 · 5 Gocce",
      "🌍 Exported to 30+ countries worldwide",
    ],
  },
  {
    slug: "fonte-di-foiano-toscano-igp",
    name: "Fonte di Foiano Toscano IGP 500ml",
    producer: "Società Agricola Fonte di Foiano",
    producerSlug: "fonte-di-foiano",
    region: "Tuscany",
    country: "Italy",
    cultivar: "Blend",
    intensity: "Medium",
    category: "olive-oil",
    organic: false,
    signatureAward: "Leone d'Oro IGP #1",
    awardYear: 2026,
    imagePath: "/images/bottles/toscano-igp-touming.png",
    tastingNotes: ["Artichoke", "Tomato Leaf", "Bitter Almond", "Wild Herbs", "Pepper"],
    pairings: ["Ribollita", "Grilled Vegetables", "Hard Cheeses", "Beef Tagliata", "Crostini"],
    description:
      "The Toscano IGP is a blend of classical Tuscan cultivars assembled to express the regional profile in a single bottle. Artichoke and tomato leaf lead, supported by bitter almond and herbs, with a clean peppery close that holds up to traditional Tuscan cooking.",
    producerBlurb:
      "Società Agricola Fonte di Foiano composes the IGP each year from estate-grown Frantoio, Leccino, Moraiolo, and Pendolino — picked separately, milled within hours, then assembled to a target sensory profile that has earned Leone d'Oro recognition.",
    pricing: { originalCny: 358, saleCny: 179, discountPct: 50 },
    freshnessTag: {
      bestBefore: "Best Before: 19 May 2026",
      storage: ["Climate-Controlled Storage", "稳控仓储 · 避光保存"],
      guarantee: "Quality Guaranteed",
    },
    subtitle:
      "Società Agricola Fonte di Foiano · Castagneto Carducci, Bolgheri · Tuscany",
    cardAwards: [
      "Flos Olei 2026 · Farm of the Year · 99/100",
      "Gambero Rosso · Tre Foglie · 10 Consecutive Years",
      "Bibenda 2025 · 5 Gocce",
    ],
    awards: [
      "🏆 Flos Olei 2026 · The Best · Farm of the Year · 99/100",
      "🏆 Flos Olei 2025 · 99/100",
      "🏆 Flos Olei 2024 · 99/100",
      "⭐ Gambero Rosso · Tre Foglie · 10 consecutive years · Annual Star",
      "🌿 Bibenda 2025 · 5 Gocce",
      "🌍 Exported to 30+ countries worldwide",
    ],
  },
  {
    slug: "frantoio-galioto-dop",
    name: "Frantoio Galioto 04 DOP 500ml",
    producer: "Frantoio Galioto",
    producerSlug: "frantoio-galioto",
    region: "Sicily",
    country: "Italy",
    cultivar: "Tonda Iblea & Moresca",
    intensity: "Medium",
    category: "olive-oil",
    organic: false,
    signatureAward: "DOP Monti Iblei",
    awardYear: 2026,
    imagePath: "/images/bottles/Galioto-04 DOP .png",
    subtitle: "Frantoio Galioto · Ferla, Siracusa · Sicily",
    tags: [
      "Italy",
      "DOP Monti Iblei",
      "Tonda Iblea & Moresca",
      "Light-Medium",
      "4 Generations",
      "Cold Extracted",
    ],
    tastingNotes: ["Clean", "Sweet", "Herbal", "Green Tomato", "Peppery Finish"],
    pairings: ["Salads", "Seafood", "Legumes", "Cold Dishes"],
    description:
      "From the ancient limestone plateaus of the Monti Iblei in southeastern Sicily, the Galioto family has cultivated olives for four generations across 100 hectares with over 20,000 trees. Handpicked at the turning point, cold-extracted within 24 hours, and stored under nitrogen — this oil preserves the most vibrant expression of Sicilian terroir.",
    tastingProse:
      "Clean and sweet with herbal notes, green tomato, long peppery finish. High polyphenol content.",
    producerBlurb:
      "Now in its fourth generation, the Galioto family farms 100 hectares of olive groves across the limestone plateau of the Monti Iblei, milling estate Tonda Iblea and Moresca at the family's continuous cold-extraction plant in Ferla.",
    awards: [
      "Flos Olei 2025 · Best DOP/IGP",
      "Bibenda 2024",
      "Bibenda 2025",
      "Sol d'Oro 2024",
      "BIOL 2025",
      "Merum 2023",
      "JOOP 2018",
      "Gambero Rosso",
      "Slow Food Italia",
    ],
    classificationOverride: [
      { label: "Origin", value: "Sicily, Italy" },
      { label: "Variety", value: "Tonda Iblea 70% & Moresca 30%" },
      { label: "Certification", value: "DOP Monti Iblei" },
      { label: "Intensity", value: "Light-Medium Fruitiness" },
      { label: "Altitude", value: "500–600m Limestone Plateau" },
    ],
    statusBadge: "Coming Soon",
    harvestBadge: "2025/2026 New Harvest",
  },
  {
    slug: "olivia-suprema-evoo",
    name: "Oliva Suprema® · Extra Virgin Olive Oil",
    producer: "Olio Fabbri",
    producerSlug: "olio-fabbri",
    region: "European Selection",
    country: "Europe",
    cultivar: "Coratina, Arbequina & Koroneiki",
    intensity: "Medium",
    category: "olive-oil",
    organic: false,
    signatureAward: "100% EVOO",
    awardYear: 2026,
    imagePath: "/images/bottles/OlivaSuprema-EU Blend EVOO.png",
    subtitle: "By Olio Fabbri × Norenfoods · European Selection · 1L",
    tags: [
      "European Blend",
      "Cold Extracted",
      "Filtered",
      "3 Cultivars",
      "Noren Exclusive",
    ],
    tastingNotes: [
      "Fresh Olive",
      "Herbaceous",
      "Green Tomato",
      "Young Almond",
      "Fresh Grass",
      "Walnut",
    ],
    pairings: ["Mixed Salads", "Grilled Vegetables", "Pasta", "Fresh Cheeses", "White Fish"],
    description:
      "A curated blend of three Mediterranean cultivars — Coratina (Italy), Arbequina (Spain), and Koroneiki (Greece) — selected in the right proportion to deliver distinctive taste and elegance. Cold extracted, filtered, and bottled exclusively for Norenfoods. A journey through the most celebrated olive-growing regions of the Mediterranean.",
    tastingProse:
      "Full-bodied and well-balanced. Clean, persistent flavor of fresh olive with herbaceous and green tomato hints, light notes of young almond. Delicate scent of fresh grass with shades of green olive, floral hints of almond and walnut.",
    producerBlurb:
      "Olio Fabbri sources single-cultivar lots from estate partners across Italy, Spain, and Greece, milling each component in its country of origin and assembling the final blend in-house against a fixed sensory target reviewed harvest by harvest.",
    pricing: { saleCny: 179 },
    freshnessTag: {
      bestBefore: "Best Before: 12 Oct 2027",
      storage: ["Climate-Controlled Storage · 稳控仓储"],
    },
  },
  {
    slug: "frantoio-romano-ortice-n01",
    name: "Frantoio Romano Ortice N.01 500ml",
    producer: "Frantoio Romano",
    producerSlug: "frantoio-romano",
    region: "Campania",
    country: "Italy",
    cultivar: "Ortice",
    intensity: "Medium-Robust",
    category: "olive-oil",
    organic: false,
    signatureAward: "Bibenda 5 Drops",
    awardYear: 2026,
    imagePath: "/images/bottles/olio_N01.png",
    subtitle: "Frantoio Romano · Benevento, Campania · Italy",
    tags: [
      "Italy",
      "Ortice",
      "Medium-Robust",
      "Monovarietal",
      "Campania",
      "Organic Certified",
    ],
    tastingNotes: [
      "Freshly Cut Grass",
      "Officinal Herbs",
      "Artichoke",
      "Green Tomato",
      "Chilli",
      "Radish",
      "Bitter Chicory",
    ],
    pairings: ["Grilled Red Meat", "Bean Soups", "Bitter Greens", "Bruschetta", "Aged Cheeses"],
    description:
      "Frantoio Romano's most representative line — the oil that brought this Sannio estate to world recognition. Cold-extracted from Ortice olives grown on centuries-old trees near Mount Taburno, Benevento. Opens with intense vegetal and herbaceous scents: freshly cut grass, officinal herbs, artichoke and green tomato. Balanced and harmonious on the palate with spicy notes of chilli, radish and bitter chicory. Certified IOO% High Quality with full supply chain traceability.",
    descriptionZh:
      "弗兰托伊奥·罗马诺酒庄最具代表性的产品线，令该产地在全球橄榄油界享誉盛名。采用贝内文托塔布诺山脚下百年树龄Ortice品种橄榄冷压萃取。香气浓郁，带有青草、药草、朝鲜蓟与绿番茄的清新气息。口感均衡和谐，辣椒、萝卜与苦菊苣的辛辣层次分明。通过IOO%高品质认证，全程供应链可追溯。",
    producerBlurb:
      "Frantoio Romano is a family-run Sannio estate at the foot of Mount Taburno in Benevento, Campania. Centuries-old Ortice groves are hand-picked and cold-extracted within hours, with full supply chain traceability and IOO% High Quality certification.",
    producerBlurbZh:
      "Frantoio Romano是位于坎帕尼亚大区贝内文托省塔布诺山脚下的桑尼奥家族酒庄。庄园保留百年Ortice橄榄树，人工采摘后数小时内即完成冷压萃取，全程供应链可追溯，通过IOO%高品质认证。",
    cardAwards: [
      "Gambero Rosso",
      "Bibenda · 5 Drops",
      "Olive Japan · Gold",
    ],
    awards: [
      "Gambero Rosso",
      "Bibenda · 5 Drops",
      "Olive Japan · Gold",
      "L'Oro d'Italia",
      "Slow Food Presidium",
    ],
  },
  {
    slug: "frantoio-romano-racioppella-n03",
    name: "Frantoio Romano Racioppella N.03 500ml",
    producer: "Frantoio Romano",
    producerSlug: "frantoio-romano",
    region: "Campania",
    country: "Italy",
    cultivar: "Racioppella",
    intensity: "Medium",
    category: "olive-oil",
    organic: false,
    signatureAward: "Native Cultivar",
    awardYear: 2026,
    imagePath: "/images/bottles/olio_ortice_riserva.png",
    subtitle: "Frantoio Romano · Benevento, Campania · Italy",
    tags: [
      "Italy",
      "Racioppella",
      "Medium",
      "Monovarietal",
      "Campania",
      "Native Cultivar",
    ],
    tastingNotes: [
      "Green Olive",
      "Unripe Tomato",
      "Artichoke",
      "Celery",
      "Unripe Fruit",
    ],
    pairings: ["White Fish", "Fresh Cheeses", "Spring Vegetables", "Carpaccio", "Light Salads"],
    description:
      "Frantoio Romano's third premium line — a rare indigenous cultivar grown exclusively on the ancient Samnite hills of Ponte, Benevento. Cold-extracted from Racioppella olives at the veraison stage. Clear emerald green color. On the nose: medium-intense fruitiness of still-green olives, unripe tomato, artichoke, celery and unripe fruit. On the palate: delicate, fluid and smooth with a pleasant balance of sweet and bitter, closing with a light spicy note.",
    descriptionZh:
      "弗兰托伊奥·罗马诺第三款精品产品线——稀有本土Racioppella品种，仅产于贝内文托蓬特地区古老的萨姆尼特山丘。在橄榄转色期精心采摘，冷压萃取。色泽清澈翠绿。香气呈中等浓郁果香，带有青橄榄、未熟番茄、朝鲜蓟、芹菜与未熟水果的气息。口感细腻流畅，甜苦均衡，收尾带有轻盈辛辣感。",
    producerBlurb:
      "Frantoio Romano is a family-run Sannio estate at the foot of Mount Taburno in Benevento, Campania. The N.03 cuvée is drawn from Racioppella, a rare indigenous cultivar found only on the Samnite hills of Ponte — hand-picked at veraison and cold-extracted within hours to preserve aromatic delicacy.",
    producerBlurbZh:
      "Frantoio Romano是位于坎帕尼亚大区贝内文托省塔布诺山脚下的桑尼奥家族酒庄。N.03选用稀有本土品种Racioppella，仅产于蓬特地区萨姆尼特山丘，在橄榄转色期人工采摘并于数小时内冷压萃取，保留其细腻芬芳。",
  },
  {
    slug: "bonamini-dop-veneto-valpolicella",
    name: "Bonamini DOP Veneto Valpolicella 500ml",
    producer: "Frantoio Bonamini",
    producerSlug: "frantoio-bonamini",
    region: "Veneto",
    country: "Italy",
    cultivar: "Grignano & Favarol",
    intensity: "Light-Medium",
    category: "olive-oil",
    organic: false,
    signatureAward: "Flos Olei Hall of Fame",
    awardYear: 2025,
    imagePath:
      "/images/bottles/olio-extravergine-oliva-veneto-valpolicella-frantoio-bonamini-1-496x2048.png",
    subtitle: "Frantoio Bonamini · Illasi Hills, Verona · Veneto · Italy",
    tags: [
      "Italy",
      "Grignano & Favarol",
      "Light-Medium",
      "DOP Veneto Valpolicella",
      "Hand Harvested",
      "Veneto",
    ],
    tastingNotes: [
      "Banana",
      "Lettuce",
      "Green Apple",
      "Mint",
      "Grass",
      "Sweet Almond",
    ],
    pairings: ["Carpaccio", "White Fish", "Risotto", "Fresh Cheeses", "Spring Salads"],
    description:
      "The flagship product of Frantoio Bonamini — a family-run estate in the Illasi Hills northeast of Verona, producing olive oil since 1965. Grown on hand-harvested terraces in the same hills famed for Amarone wine, this DOP-certified oil is made from indigenous Grignano and Favarol varieties, cold-extracted the same day of harvest. Light and fruity with a fresh, elegant profile: aromas of banana, lettuce, green apple, mint and grass. Round and creamy on the palate with medium bitterness, a light peppery finish and a sweet almond close. Acidity: 0.15%.",
    descriptionZh:
      "博纳米尼弗兰托伊奥的旗舰产品——维罗纳东北伊拉西山丘家族酒庄，自1965年起专注橄榄油生产。橄榄树种植于因阿马罗内葡萄酒而闻名的同一山丘梯田，全程人工采摘。采用本地Grignano与Favarol品种，当日冷压萃取。口感轻盈果香，清新优雅：香蕉、生菜、青苹果、薄荷与青草气息。口感圆润顺滑，中度苦味，轻盈辛辣收尾，带甜杏仁余韵。酸度仅0.15%。",
    producerBlurb:
      "Frantoio Bonamini is a family-run estate in the Illasi Hills northeast of Verona, producing extra virgin olive oil since 1965. Indigenous Grignano and Favarol olives are hand-harvested on terraced groves in the hills famed for Amarone, then milled the same day at the family's own frantoio under tight quality control.",
    producerBlurbZh:
      "Frantoio Bonamini是位于维罗纳东北伊拉西山丘的家族酒庄，自1965年起专注特级初榨橄榄油生产。本土Grignano与Favarol品种橄榄在以阿马罗内葡萄酒闻名的梯田上人工采摘，当日于自家压榨厂完成冷压萃取，严格把控品质。",
    cardAwards: [
      "Flos Olei · Hall of Fame · 100/100",
      "L'Orciolo d'Oro · Gold",
      "NYIOOC · Gold",
    ],
    awards: [
      "Flos Olei 2025 · Hall of Fame · 100/100",
      "Flos Olei 2024 · Hall of Fame · 5th Consecutive Year · 100/100",
      "Flos Olei 2019 · Best EVOO PDO/PGI",
      "L'Orciolo d'Oro 2022 · Gold",
      "NYIOOC · Gold",
    ],
  },
  {
    slug: "quattrociocchi-olivastro",
    name: "Quattrociocchi Olivastro Organic 500ml",
    producer: "Quattrociocchi",
    producerSlug: "quattrociocchi",
    region: "Lazio",
    country: "Italy",
    cultivar: "Itrana",
    intensity: "Robust",
    category: "olive-oil",
    organic: true,
    signatureAward: "Flos Olei Hall of Fame",
    awardYear: 2026,
    imagePath: "/images/bottles/Quattrociocchi-Olivastro-500ml.png",
    subtitle: "Quattrociocchi · Alatri, Lazio · Italy",
    tags: ["Italy", "Itrana", "Robust", "Monovarietal", "Organic", "Lazio"],
    tastingNotes: [
      "Grass",
      "Artichoke",
      "Green Tomato",
      "Apple",
      "Green Almond",
    ],
    pairings: ["Grilled Red Meat", "Bean Soups", "Bitter Greens", "Bruschetta", "Aged Cheeses"],
    description:
      "From the ancient organic olive groves of Alatri in the heart of Ciociaria, Lazio — a family estate founded in 1888. Produced exclusively from 100% Itrana variety olives. Robust green fruitiness with complex aromas of grass, artichoke, green tomato and apple. Balanced bitterness and spiciness with hints of green almond. A two-time Flos Olei Best in World winner and Hall of Fame honoree.",
    descriptionZh:
      "来自拉齐奥奇奥恰里亚中心阿拉特里的百年有机橄榄庄园，始建于1888年。100% Itrana品种有机橄榄冷压萃取。浓郁绿色果香，带有青草、朝鲜蓟、绿番茄与苹果的复杂气息。苦味与辛辣感均衡，收尾带青杏仁余韵。两度荣获Flos Olei全球最佳，入选名人堂。",
    producerBlurb:
      "Quattrociocchi is a family estate founded in 1888 in Alatri, in the heart of Ciociaria, Lazio. The family farms organic Itrana groves on the hills of the Ernici mountains, milling at their own frantoio and aiming for Best-in-World level extractions year after year.",
    producerBlurbZh:
      "Quattrociocchi酒庄始建于1888年，位于拉齐奥奇奥恰里亚中心阿拉特里。家族在埃尔尼齐山丘种植有机Itrana品种橄榄树，于自家压榨厂萃取，年年追求世界最佳水准。",
    cardAwards: [
      "Flos Olei 2026 · Hall of Fame · 100/100",
      "NYIOOC · Gold",
      "Olive Japan · Gold",
    ],
    awards: [
      "Flos Olei 2026 · Hall of Fame · 100/100",
      "NYIOOC · Gold",
      "Olive Japan · Gold",
      "Sol d'Oro · Gold",
      "Ercole Olivario · 1st",
    ],
  },
  {
    slug: "quattrociocchi-superbo",
    name: "Quattrociocchi Superbo Organic 500ml",
    producer: "Quattrociocchi",
    producerSlug: "quattrociocchi",
    region: "Lazio",
    country: "Italy",
    cultivar: "Moraiolo",
    intensity: "Extreme",
    category: "olive-oil",
    organic: true,
    signatureAward: "Flos Olei Hall of Fame",
    awardYear: 2025,
    imagePath: "/images/bottles/Quattrociocchi-Superbo-500ml.png",
    subtitle: "Quattrociocchi · Alatri, Lazio · Italy",
    tags: [
      "Italy",
      "Moraiolo",
      "Extreme",
      "Monovarietal",
      "Organic",
      "High Polyphenol",
      "Lazio",
    ],
    tastingNotes: [
      "Fresh-Cut Grass",
      "Artichoke",
      "Mint",
      "Sage",
      "Basil",
    ],
    pairings: ["Grilled Red Meat", "Game", "Aged Pecorino", "Hearty Soups", "Robust Stews"],
    description:
      "Not for the faint of heart — the most powerful expression from Quattrociocchi. Produced exclusively from organic Moraiolo variety olives. Extreme intensity with bold aromas of fresh-cut grass and artichoke, aromatic hints of mint, sage and basil. Strong, pungent and beautifully balanced — for the true connoisseur. 800 mg/kg polyphenols. Best in World multiple award winner.",
    descriptionZh:
      "Quattrociocchi最具冲击力的产品——100% 有机Moraiolo品种冷压萃取。极强烈度，浓郁的青草与朝鲜蓟香气，伴随薄荷、鼠尾草与罗勒的芳香气息。强劲、辛辣、均衡——真正橄榄油鉴赏家的选择。多酚含量高达800mg/kg，多次荣获全球最佳。",
    producerBlurb:
      "Quattrociocchi is a family estate founded in 1888 in Alatri, Lazio. Superbo is the house's most extreme cuvée: organic Moraiolo, hand-picked very early and cold-extracted within hours to lock in 800 mg/kg of polyphenols.",
    producerBlurbZh:
      "Quattrociocchi酒庄始建于1888年，位于拉齐奥阿拉特里。Superbo是酒庄最强烈的产品线，选用有机Moraiolo品种，极早期人工采摘并于数小时内冷压萃取，多酚含量稳定锁定在800mg/kg。",
    cardAwards: [
      "Flos Olei 2025 · Hall of Fame · 100/100",
      "BIOL · 1st Best Organic",
      "Il Magnifico · Gold",
    ],
    awards: [
      "Flos Olei 2025 · Hall of Fame · 100/100",
      "Il Magnifico 2022 · Gold",
      "BioL 2026 · Gold",
      "BIOL · 1st Best Organic",
      "Sol d'Argento",
    ],
  },
  {
    slug: "mate-viola-tonda",
    name: "Mate Viola Tonda 250ml",
    producer: "Mate Olive Oil",
    producerSlug: "mate-olive-oil",
    region: "Istria",
    country: "Croatia",
    cultivar: "Buža",
    intensity: "Medium",
    category: "olive-oil",
    organic: true,
    signatureAward: "Flos Olei 100/100",
    awardYear: 2024,
    imagePath: "/images/bottles/mate-olive-oil-viola-tonda_EN.png",
    subtitle: "Mate Olive Oil · Zambratija, Istria · Croatia",
    tags: ["Croatia", "Buža", "Medium", "Monovarietal", "Organic", "Istria", "Kosher"],
    tastingNotes: [
      "Almond",
      "Apple",
      "Banana",
      "Flowers",
      "Medicinal Herbs",
      "Pepper",
      "Thistle",
    ],
    pairings: ["Carpaccio", "White Fish", "Spring Vegetables", "Fresh Cheeses", "Bruschetta"],
    description:
      "From a visionary estate founded in 1994 by Mate Vekić on the Adriatic coast of Istria — Croatia's first olive oil to score 100/100 in Flos Olei. Viola Tonda is extracted from the native Buža variety, named for the chromatic journey of the olive fruit from beige to pink to deep purple at veraison. Green and fresh fruitiness of medium intensity with hints of almond, apple, banana and a touch of flowers. The initial sweetness gives way to a harmonious bitter-spicy balance, never aggressive — enveloping and persistent. Elegant almond notes, medicinal herbs, pepper and thistle.",
    descriptionZh:
      "来自1994年Mate Vekić在伊斯特拉亚得里亚海岸创立的传奇庄园——克罗地亚首款Flos Olei满分100/100橄榄油。Viola Tonda采用本土Buža品种榨制，标签色彩灵感来自橄榄果从米白到粉红再到深紫的成熟变化过程。清新中等果香，带杏仁、苹果、香蕉与淡花香气息。初始甜感渐转均衡苦辣，从不强烈——包裹感强，余韵持久。杏仁、药草、胡椒与蓟的优雅尾韵。",
    producerBlurb:
      "Mate Olive Oil is a visionary Istrian estate founded in 1994 by Mate Vekić in Zambratija, on Croatia's Adriatic coast. The estate works native varieties — Buža foremost — under organic and kosher protocols, and was the first Croatian producer to reach Flos Olei's 100/100.",
    producerBlurbZh:
      "Mate橄榄油庄园由Mate Vekić于1994年在克罗地亚亚得里亚海岸伊斯特拉Zambratija创立。庄园以本土品种为核心，主打Buža，采用有机与犹太洁食标准生产，是首个获得Flos Olei满分100/100的克罗地亚酒庄。",
    cardAwards: [
      "Flos Olei 2024 · 100/100 · First Croatian Oil",
      "Flos Olei · Best Packaging",
      "Flos Olei · Best Estate",
    ],
    awards: [
      "Flos Olei 2024 · 100/100 · First Croatian Oil",
      "Flos Olei · Best Packaging",
      "Flos Olei · Best Estate",
    ],
  },
  {
    slug: "mate-limone",
    name: "Mate Limone Condimento 250ml",
    producer: "Mate Olive Oil",
    producerSlug: "mate-olive-oil",
    region: "Istria",
    country: "Croatia",
    cultivar: "Olive & Lemon Condiment",
    intensity: "Light",
    category: "olive-oil",
    organic: true,
    signatureAward: "Condimento",
    awardYear: 2026,
    imagePath: "/images/bottles/mate-olive-oil-limone_EN.png",
    subtitle: "Mate Olive Oil · Zambratija, Istria · Croatia",
    tags: ["Croatia", "Olive & Lemon", "Light", "Condiment", "Organic", "Istria"],
    tastingNotes: ["Fresh Lemon", "Citrus Zest", "Istrian EVOO", "Bright", "Clean"],
    pairings: ["Seafood", "Salads", "Carpaccio", "White Fish", "Fresh Cheeses"],
    description:
      "A cold-pressed condiment crafted by Mate Olive Oil using fresh lemons and extra virgin olive oil from their organic Istrian estate. Vibrant citrus aroma with the clean freshness of Istrian olive oil. Ideal for raw use: drizzled over seafood, salads, carpaccio, white fish and fresh cheeses. A refined finishing condiment.",
    descriptionZh:
      "Mate橄榄油庄园采用有机伊斯特拉特级初榨橄榄油与新鲜柠檬冷压调制。清新活泼的柑橘香气融合伊斯特拉橄榄油的纯净清新。适合生食点缀：海鲜、沙拉、薄切生肉、白鱼及新鲜奶酪。精致收尾调味油。",
    producerBlurb:
      "Mate Olive Oil is a visionary Istrian estate founded in 1994 by Mate Vekić in Zambratija, Croatia. The Limone condimento line cold-presses fresh lemons together with the estate's organic Istrian EVOO for a clean, citrus-forward finishing oil.",
    producerBlurbZh:
      "Mate橄榄油庄园由Mate Vekić于1994年在克罗地亚伊斯特拉Zambratija创立。Limone调味油以庄园有机伊斯特拉特级初榨橄榄油与新鲜柠檬同步冷压而成，呈现纯净清新的柑橘调收尾风味。",
  },
  {
    slug: "mate-arancia",
    name: "Mate Arancia Condimento 250ml",
    producer: "Mate Olive Oil",
    producerSlug: "mate-olive-oil",
    region: "Istria",
    country: "Croatia",
    cultivar: "Olive & Orange Condiment",
    intensity: "Light",
    category: "olive-oil",
    organic: true,
    signatureAward: "Condimento",
    awardYear: 2026,
    imagePath: "/images/bottles/mate-olive-oil-arancia_EN.png",
    subtitle: "Mate Olive Oil · Zambratija, Istria · Croatia",
    tags: ["Croatia", "Olive & Orange", "Light", "Condiment", "Organic", "Istria"],
    tastingNotes: ["Sweet Orange", "Citrus Warmth", "Herbal", "Istrian EVOO", "Aromatic"],
    pairings: ["Salads", "Duck", "Pork", "Desserts", "Aged Cheeses"],
    description:
      "A cold-pressed condiment from Mate Olive Oil combining organic extra virgin olive oil from Istria with fresh oranges. Sweet citrus warmth balanced with the clean herbal character of Istrian oil. Perfect raw on salads, duck, pork, desserts and aged cheeses. A unique and aromatic finishing oil.",
    descriptionZh:
      "Mate橄榄油采用有机伊斯特拉特级初榨橄榄油与新鲜橙子冷压调制。甜润柑橘温暖感与伊斯特拉橄榄油清新草本特质完美融合。适合生食：沙拉、鸭肉、猪肉、甜点及陈年奶酪。独特芳香的收尾调味油。",
    producerBlurb:
      "Mate Olive Oil is a visionary Istrian estate founded in 1994 by Mate Vekić in Zambratija, Croatia. The Arancia condimento line cold-presses fresh oranges together with the estate's organic Istrian EVOO for a warm, sweet-citrus finishing oil.",
    producerBlurbZh:
      "Mate橄榄油庄园由Mate Vekić于1994年在克罗地亚伊斯特拉Zambratija创立。Arancia调味油以庄园有机伊斯特拉特级初榨橄榄油与新鲜橙子同步冷压而成，呈现温润甜橙的收尾风味。",
  },
  {
    slug: "nonno-salvatore-le-tre-colonne",
    name: "Nonno Salvatore Le Tre Colonne 500ml",
    producer: "Le Tre Colonne",
    producerSlug: "le-tre-colonne",
    region: "Puglia",
    country: "Italy",
    cultivar: "Bella di Cerignola",
    intensity: "Light",
    category: "olive-oil",
    organic: false,
    signatureAward: "Kid-Friendly",
    awardYear: 2026,
    imagePath: "/images/bottles/le tre colonne kis (1).png",
    subtitle: "Le Tre Colonne · Puglia · Italy",
    tags: [
      "Italy",
      "Bella di Cerignola",
      "Light",
      "Monovarietal",
      "Puglia",
      "Kid-Friendly",
    ],
    tastingNotes: ["Fresh Fava Beans", "Spring Peas", "Light Green", "Gentle"],
    pairings: ["Vegetable Creams", "Apulian Bruschetta", "Seafood", "Children's Meals"],
    description:
      "100% Bella di Cerignola — a rare native Apulian variety harvested in early November. Light and delicate, with an intense scent of fresh fava beans and spring peas. The taste is gentle and ideal for weaning children and sensitive palates. Filtered oil, green with gold reflections. Perfect for vegetable creams, Apulian bruschetta and seafood.",
    descriptionZh:
      "100% Bella di Cerignola——普利亚稀有本土品种，于11月初采摘。口感轻盈细腻，香气浓郁带新鲜蚕豆与春豌豆气息。口味温和，适合儿童辅食与敏感味蕾。过滤型，色泽碧绿带金色光泽。适合蔬菜奶油汤、普利亚烤面包片及海鲜菜肴。",
    producerBlurb:
      "Le Tre Colonne is an Apulian family estate working rare native cultivars. The Nonno Salvatore line uses 100% Bella di Cerignola olives, picked early in November and cold-extracted to keep the oil light enough for children and sensitive palates.",
    producerBlurbZh:
      "Le Tre Colonne是普利亚家族酒庄，专注稀有本土品种。Nonno Salvatore产品线选用100% Bella di Cerignola橄榄，于11月初采摘并冷压萃取，保留轻盈口感，适合儿童与味蕾敏感者。",
  },
  {
    slug: "viola-il-sincero",
    name: "Viola Il Sincero 500ml",
    producer: "Azienda Agraria Viola",
    producerSlug: "azienda-agraria-viola",
    region: "Umbria",
    country: "Italy",
    cultivar: "Moraiolo",
    intensity: "Robust",
    category: "olive-oil",
    organic: true,
    signatureAward: "Gambero Rosso Tre Foglie",
    awardYear: 2026,
    imagePath: "/images/bottles/Viola-Sincero-500ml.png",
    subtitle: "Azienda Agraria Viola · Umbria · Italy",
    tags: ["Italy", "Moraiolo", "Robust", "Monovarietal", "Umbria", "Organic"],
    tastingNotes: [
      "Freshly Mowed Grass",
      "Thistle",
      "Mint",
      "Wild Rosemary",
      "Chicory",
    ],
    pairings: ["Grilled Red Meat", "Bean Soups", "Bitter Greens", "Bruschetta", "Aged Cheeses"],
    description:
      "A monocultivar of Moraiolo from centuries-old olive trees rooted in the stony, steep hills of Umbria — cultivated according to tradition. Hand-picked at the beginning of ripening. Intense emerald green. Broad, elegant and complex on the nose with rich vegetal notes of freshly mowed grass and thistle, balsamic hints of mint and wild rosemary. Complex and persistent on the palate, with a predominance of thistle and chicory, well-balanced bitter and spicy notes.",
    descriptionZh:
      "翁布里亚百年橄榄树上的Moraiolo单品种油，生长于石质陡峭山坡，按传统方式耕种。转色初期手工采摘。色泽深翠绿。香气宽广优雅复杂，带有浓郁的青草、蓟草植物气息，以及薄荷与野迷迭香的香脂提示。口感复杂持久，以蓟草与菊苣为主调，苦味与辛辣均衡协调。",
    producerBlurb:
      "Azienda Agraria Viola farms centuries-old Moraiolo groves on the stony, steep hills of Umbria. Hand-picked at the beginning of ripening and cold-extracted in-house, Il Sincero is the estate's most robust expression of the cultivar.",
    producerBlurbZh:
      "Azienda Agraria Viola在翁布里亚石质陡峭山丘上经营百年Moraiolo橄榄林。在转色初期人工采摘并于自家压榨厂冷压萃取，Il Sincero是酒庄最强烈的Moraiolo品种表达。",
    cardAwards: [
      "Gambero Rosso · Tre Foglie",
      "Flos Olei",
      "NYIOOC · Gold",
    ],
    awards: [
      "Gambero Rosso · Tre Foglie",
      "Flos Olei",
      "Slow Food Presidium",
      "NYIOOC · Gold",
    ],
  },
  {
    slug: "masoni-becciu-alphabetum",
    name: "Masoni Becciu Alphabetum 500ml",
    producer: "Masoni Becciu",
    producerSlug: "masoni-becciu",
    region: "Sardinia",
    country: "Italy",
    cultivar: "Ispiritu Sardu",
    intensity: "Medium-Robust",
    category: "olive-oil",
    organic: true,
    signatureAward: "Flos Olei 96/100",
    awardYear: 2025,
    imagePath: "/images/bottles/Masoni Becciu 500ml.png",
    subtitle: "Masoni Becciu · Villacidro, Sardinia · Italy",
    tags: [
      "Italy",
      "Native Sardinian",
      "Medium-Robust",
      "Organic",
      "Sardinia",
      "Indigenous Cultivar",
    ],
    tastingNotes: [
      "Green Olives",
      "Sweet Tomato",
      "Aromatic Herbs",
      "Green Tomato",
      "Almond",
      "Medicinal Herbs",
    ],
    pairings: ["Grilled Meats", "Mediterranean Seafood", "Roasted Vegetables", "Pecorino", "Bruschetta"],
    description:
      "From the ancient hills of Villacidro in southern Sardinia — a certified organic oil from rare indigenous Sardinian cultivars. Pervasive fresh notes of green olives on the nose with sweet tomato and aromatic herbs, accompanied by elegant balsamic counterpoints. A pleasant balance of bitterness and intense spiciness on the palate, with hints of green tomato and almond, and notes of medicinal herbs. A fine oil with embracing aroma and agreeable persistence.",
    descriptionZh:
      "来自撒丁岛南部维拉西德罗古老山丘——采用稀有本土撒丁品种认证有机橄榄油。鼻腔充满浓郁新鲜绿橄榄气息，伴随甜番茄与芳香草本，辅以优雅香脂对位。口感苦味与浓郁辛辣均衡怡人，带绿番茄与杏仁提示，以及药草气息。香气包裹感强，余韵悦人。",
    producerBlurb:
      "Masoni Becciu farms ancient indigenous Sardinian cultivars — Ispiritu Sardu among them — on the hills above Villacidro in southern Sardinia. The estate is fully certified organic and presses its olives at its own frantoio within hours of harvest.",
    producerBlurbZh:
      "Masoni Becciu在撒丁岛南部维拉西德罗山丘上种植古老的本土撒丁品种，包括Ispiritu Sardu。酒庄全面通过有机认证，于自家压榨厂数小时内完成冷压萃取。",
    cardAwards: [
      "Flos Olei 2025 · 96/100",
      "NYIOOC · Gold",
      "Bibenda · 4 Gocce",
    ],
    awards: [
      "Flos Olei 2025 · 96/100",
      "NYIOOC · Gold",
      "Slow Food Presidium",
      "Bibenda · 4 Gocce",
    ],
  },
  {
    slug: "de-carlo-tenuta-torre-di-mossa-dop",
    name: "De Carlo Tenuta Torre di Mossa DOP 500ml",
    producer: "Olio De Carlo",
    producerSlug: "olio-de-carlo",
    region: "Puglia",
    country: "Italy",
    cultivar: "Coratina",
    intensity: "Robust",
    category: "olive-oil",
    organic: false,
    signatureAward: "DOP Terra di Bari Bitonto",
    awardYear: 2025,
    imagePath: "/images/bottles/1288-TENUTA-TORRE-DI-MOSSA-500ML.png",
    subtitle: "Olio De Carlo · Bitritto, Puglia · Italy",
    tags: [
      "Italy",
      "Coratina",
      "Robust",
      "Monovarietal",
      "DOP",
      "Puglia",
      "Family Estate",
    ],
    tastingNotes: ["Fresh-Cut Grass", "Artichoke", "Wild Herbs", "Bitter", "Pungent"],
    pairings: ["Grilled Red Meat", "Bean Soups", "Bitter Greens", "Bruschetta", "Aged Cheeses"],
    description:
      "Torre di Mossa is the historic estate of the De Carlo family — the birthplace of their signature extra virgin olive oil. Grown on the family's ancestral grounds in Bitritto, Puglia. The Coratina cultivar expresses its full power here: intense green fruitiness, bold aromas of fresh-cut grass, artichoke and wild herbs. Powerfully bitter and pungent — persistent, complex and deeply structured. DOP Terra di Bari Bitonto certified.",
    descriptionZh:
      "托雷·迪·莫萨是德卡洛家族的历史庄园——其标志性特级初榨橄榄油的诞生地。种植于普利亚比特里托家族祖传土地上。Coratina品种在此展现完整力量：浓郁绿色果香，大胆的青草、朝鲜蓟与野草本香气。苦味与辛辣强劲持久，层次复杂，结构深厚。DOP Terra di Bari Bitonto认证。",
    producerBlurb:
      "Olio De Carlo is a multigenerational Apulian family estate based in Bitritto. Torre di Mossa is the historic ancestral grove where the family first pressed its signature Coratina — still milled on-site at the family's own frantoio under DOP Terra di Bari Bitonto discipline.",
    producerBlurbZh:
      "Olio De Carlo是位于普利亚比特里托的多代家族酒庄。Torre di Mossa是家族最初压榨标志性Coratina的祖传橄榄园，至今仍于家族自家压榨厂按DOP Terra di Bari Bitonto标准生产。",
    cardAwards: [
      "Flos Olei 2025 · 96/100",
      "Gambero Rosso · Tre Foglie",
      "NYIOOC · Gold",
    ],
    awards: [
      "Flos Olei 2025 · 96/100",
      "Gambero Rosso · Tre Foglie",
      "NYIOOC · Gold",
      "Slow Food",
    ],
  },
  {
    slug: "aceto-del-duca",
    name: "Aceto Balsamico di Modena IGP",
    producer: "Giardini",
    producerSlug: "giardini",
    region: "Modena",
    country: "Italy",
    cultivar: "Trebbiano & Lambrusco",
    intensity: "Traditional",
    category: "balsamic",
    organic: false,
    signatureAward: "Modena IGP",
    awardYear: 2026,
    imagePath: "/images/bottles/balsamic-gia1100.png",
    subtitle: "Giardini · Modena IGP · 250ml",
    tags: ["Modena IGP", "Wood-Barrel Aged"],
    tastingNotes: ["Cooked Grape", "Dried Fig", "Soft Wood", "Caramel"],
    pairings: ["Salads", "Marinades", "Grilled Vegetables", "Everyday Cooking"],
    description:
      "Classic Balsamic Vinegar of Modena IGP. Aged in wooden barrels, rich and versatile. Perfect for dressings, marinades and everyday cooking.",
    producerBlurb:
      "Giardini operates within the Modena IGP zone, sourcing must from regional Trebbiano and Lambrusco vineyards and ageing in wooden barrels under the IGP discipline.",
    pricing: { saleCny: 198 },
  },
  {
    slug: "giardini-aceto-balsamico-modena-igp",
    name: "Aceto Balsamico di Modena IGP Qualità 12",
    producer: "Giardini",
    producerSlug: "giardini",
    region: "Modena",
    country: "Italy",
    cultivar: "Trebbiano & Lambrusco",
    intensity: "Traditional",
    category: "balsamic",
    organic: false,
    signatureAward: "Modena IGP · Qualità 12",
    awardYear: 2026,
    imagePath: "/images/bottles/balsamic-vinegar.png",
    subtitle: "Giardini · Modena IGP · 250ml",
    tags: ["Modena IGP", "12 Months Aged"],
    tastingNotes: ["Cooked Grape", "Dried Fig", "Caramel", "Soft Wood"],
    pairings: ["Mixed Salads", "Meats", "Vegetables", "Finishing"],
    description:
      "Aged a minimum of 12 months in oak and chestnut barrels. Smooth, balanced and pleasantly thick. Ideal for finishing salads, meats and vegetables.",
    producerBlurb:
      "Giardini's Qualità 12 line is selected from must aged in oak and chestnut for at least twelve months, then bottled under the Modena IGP discipline.",
    pricing: { saleCny: 328 },
  },
  {
    slug: "giardini-aceto-balsamico-dop-12",
    name: "Aceto Balsamico Tradizionale DOP Affinato",
    producer: "Giardini",
    producerSlug: "giardini",
    region: "Modena",
    country: "Italy",
    cultivar: "Trebbiano & Lambrusco",
    intensity: "Traditional",
    category: "balsamic",
    organic: false,
    signatureAward: "Modena DOP · Affinato · 12 Years",
    awardYear: 2026,
    imagePath: "/images/bottles/balsamic-vinegar-dop-12.png",
    subtitle: "Giardini · Modena DOP · 100ml · 12 Years Aged",
    tags: ["Modena DOP", "Affinato", "12 Years Aged"],
    tastingNotes: ["Cooked Grape", "Fig", "Wood Spice", "Caramel", "Plum"],
    pairings: ["Parmigiano", "Roasted Meats", "Desserts"],
    description:
      "Minimum 12 years aged in a battery of barrels — oak, chestnut, mulberry, cherry, juniper. Thick, velvety and complex. Bottled in the iconic Giugiaro-designed 100ml DOP bottle. Drizzle over Parmigiano, roasted meats or desserts.",
    producerBlurb:
      "Giardini follows the traditional DOP cask hierarchy — oak, chestnut, mulberry, cherry, juniper — racking small volumes annually to evaporate water and concentrate the must without additives.",
    pricing: { saleCny: 1428 },
  },
  {
    slug: "giardini-aceto-balsamico-dop-25",
    name: "Aceto Balsamico Tradizionale DOP Extravecchio",
    producer: "Giardini",
    producerSlug: "giardini",
    region: "Modena",
    country: "Italy",
    cultivar: "Trebbiano & Lambrusco",
    intensity: "Traditional",
    category: "balsamic",
    organic: false,
    signatureAward: "Modena DOP · Extravecchio · 25 Years",
    awardYear: 2026,
    imagePath: "/images/bottles/balsamic-vinegar-dop-25.png",
    subtitle: "Giardini · Modena DOP · 100ml · 25 Years Aged",
    tags: ["Modena DOP", "Extravecchio", "25 Years Aged"],
    tastingNotes: ["Cooked Grape", "Date", "Aged Wood", "Dark Caramel", "Dried Cherry"],
    pairings: ["Parmigiano", "Foie Gras", "Dark Chocolate", "Truffle", "Tasted Neat"],
    description:
      "The pinnacle of traditional balsamic. Aged minimum 25 years in progressively smaller barrels of different woods. Rich, persistent and intensely aromatic — a rare elixir to savour neat or as a finishing touch on the finest dishes.",
    producerBlurb:
      "Giardini reserves the oldest casks in the battery for the 25-year Extravecchio DOP, decanting only the smallest annual measure. Bottled at the consortium under controlled provenance.",
    pricing: { saleCny: 2188 },
  },
];

export function findFeatured(producerSlug: string, brandSlug: string): FeaturedProduct | undefined {
  return FEATURED_PRODUCTS.find(
    (p) => p.producerSlug === producerSlug && p.slug === brandSlug,
  );
}
